.386
STACK	SEGMENT	USE16	STACK
		DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
STR1	DB	'0270'
DATA	ENDS
CODE	SEGMENT	USE16
		ASSUME CS: CODE, DS: DATA, SS:STACK
START:	MOV		AX, DATA 
		LEA		DX, STR1
		MOV		AH, 9
		int 	21h
		
		
CODE	ENDS
		END		START