.386
STACK	SEGMENT	USE16	STACK
		DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
STR1	DB	'0270'
XUEHAO	DB	4 DUP(0)
DATA	ENDS
CODE	SEGMENT	USE16
		ASSUME CS: CODE, DS: DATA, SS:STACK
START:	MOV		AX, DATA
		MOV		DS, AX  
		MOV     SI, 0
		MOV		DI, 4
		
LOOPA1:	MOV		AL, [SI]+STR1		;变址寻址方式
		MOV		[SI]+XUEHAO, AL		;变量名决定段
		INC		SI
		DEC 	DI
		JNE		LOOPA1
		MOV		AH, 4CH
		INT		21H

CODE	ENDS
		END		START