.386
STACK	SEGMENT	USE16	STACK
		DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
XUEHAO	DB	4 DUP(0)
STR1	DB	'0270'
DATA	ENDS
CODE	SEGMENT	USE16
		ASSUME CS: CODE, DS: DATA, SS:STACK
		
START:	MOV		AX, DATA
		MOV		DS, AX  
		MOV		EDI, OFFSET	 XUEHAO
		MOV 	EDX, OFFSET  STR1
		MOV		CX, 4
LOOPA:	MOV		AL, [EDX]		;间接寻址方式
		MOV		[EDI], AL
		INC		EDX
		INC		EDI
		DEC 	CX
		JNE		LOOPA
		MOV		AH, 4CH
		INT		21H
CODe	ENDS
		END		START