.386
STACK	SEGMENT	USE16	STACK
		DB	200	DUP(0)
STACK	ENDS
DATA	SEGMENT	USE16
XUEHAO	DB	4 DUP(0)
STR1	DB	'0270'
DATA	ENDS
CODE	SEGMENT	USE16
		ASSUME CS: CODE, DS: DATA, SS:STACK
START:	MOV		AX, DATA
		MOV		DS, AX  
		LEA		BX,	STR1
		LEA		BP, XUEHAO
		MOV		SI, 0
		MOV     CX, 4
LOOPA:	MOV		AL, [BX][SI]		;基址加变址寻址
		MOV		DS:[BP][SI], AL
		INC		SI
		DEC 	CX
		JNE		LOOPA
		MOV		AH, 4CH
		INT		21H
CODE	ENDS
		END		START